import json
import sys
import oracledb

def create_connection():
    try:
        conn = oracledb.connect(
            user="skillshift",
            password="skillshift_pw",
            dsn="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orclpdb1)))"
        )
        return conn
    except Exception as e:
        print("Erro de conexão:", e)
        return None

def validar_str(msg):
    while True:
        valor = input(msg).strip()
        if valor:
            return valor
        print("Valor inválido.")

def validar_int(msg, minimo=0, maximo=100):
    while True:
        try:
            v = int(input(msg))
            if minimo <= v <= maximo:
                return v
            print(f"Digite um número entre {minimo} e {maximo}.")
        except:
            print("Entrada inválida.")

def exportar_json(dados, nome):
    try:
        with open(nome, "w", encoding="utf-8") as f:
            json.dump(dados, f, indent=2, ensure_ascii=False)
        print("Exportado com sucesso.")
    except Exception as e:
        print("Erro ao exportar:", e)

def criar_tabelas():
    conn = create_connection()
    if not conn:
        return
    cur = conn.cursor()
    try:
        cur.execute("CREATE TABLE professionals (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, name VARCHAR2(100), email VARCHAR2(150), role VARCHAR2(100), skill_level NUMBER)")
    except:
        pass
    try:
        cur.execute("CREATE TABLE learning_paths (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, title VARCHAR2(150), description VARCHAR2(500), duration_hours NUMBER)")
    except:
        pass
    conn.commit()
    cur.close()
    conn.close()
    print("Tabelas prontas.")

def criar_profissional():
    nome = validar_str("Nome: ")
    email = validar_str("Email: ")
    cargo = validar_str("Cargo: ")
    nivel = validar_int("Nível de habilidade (0-100): ")
    conn = create_connection()
    if not conn:
        return
    cur = conn.cursor()
    try:
        cur.execute("INSERT INTO professionals (name, email, role, skill_level) VALUES (:1, :2, :3, :4)", (nome, email, cargo, nivel))
        conn.commit()
        print("Profissional cadastrado.")
    except Exception as e:
        print("Erro:", e)
    cur.close()
    conn.close()

def listar_profissionais():
    conn = create_connection()
    if not conn:
        return
    cur = conn.cursor()
    cur.execute("SELECT * FROM professionals ORDER BY id")
    cols = [d[0].lower() for d in cur.description]
    dados = [dict(zip(cols, r)) for r in cur.fetchall()]
    for d in dados:
        print(d)
    if input("Exportar para JSON? (s/n): ").lower() == 's':
        nome = validar_str("Nome do arquivo: ")
        exportar_json(dados, nome)
    cur.close()
    conn.close()

def criar_trilha():
    titulo = validar_str("Título: ")
    desc = validar_str("Descrição: ")
    dur = validar_int("Duração (h): ", 1, 500)
    conn = create_connection()
    if not conn:
        return
    cur = conn.cursor()
    try:
        cur.execute("INSERT INTO learning_paths (title, description, duration_hours) VALUES (:1, :2, :3)", (titulo, desc, dur))
        conn.commit()
        print("Trilha criada.")
    except Exception as e:
        print("Erro:", e)
    cur.close()
    conn.close()

def listar_trilhas():
    conn = create_connection()
    if not conn:
        return
    cur = conn.cursor()
    cur.execute("SELECT * FROM learning_paths ORDER BY id")
    cols = [d[0].lower() for d in cur.description]
    dados = [dict(zip(cols, r)) for r in cur.fetchall()]
    for d in dados:
        print(d)
    if input("Exportar para JSON? (s/n): ").lower() == 's':
        nome = validar_str("Nome do arquivo: ")
        exportar_json(dados, nome)
    cur.close()
    conn.close()

def consulta_profissionais_iniciantes():
    limite = validar_int("Listar profissionais com nível abaixo de: ", 0, 100)
    conn = create_connection()
    if not conn:
        return
    cur = conn.cursor()
    cur.execute("SELECT name, role, skill_level FROM professionals WHERE skill_level < :1", (limite,))
    cols = [d[0].lower() for d in cur.description]
    dados = [dict(zip(cols, r)) for r in cur.fetchall()]
    for d in dados:
        print(d)
    if input("Exportar para JSON? (s/n): ").lower() == 's':
        nome = validar_str("Nome do arquivo: ")
        exportar_json(dados, nome)
    cur.close()
    conn.close()

def menu():
    while True:
        print("\n=== SkillShift AI ===")
        print("1 - Criar tabelas")
        print("2 - Cadastrar profissional")
        print("3 - Listar profissionais")
        print("4 - Cadastrar trilha")
        print("5 - Listar trilhas")
        print("6 - Consultar profissionais iniciantes")
        print("0 - Sair")
        opc = input("Opção: ")
        if opc == '1': criar_tabelas()
        elif opc == '2': criar_profissional()
        elif opc == '3': listar_profissionais()
        elif opc == '4': criar_trilha()
        elif opc == '5': listar_trilhas()
        elif opc == '6': consulta_profissionais_iniciantes()
        elif opc == '0':
            print("Saindo...")
            sys.exit()
        else:
            print("Opção inválida.")

if __name__ == "__main__":
    menu()